# set this to true to run unminimize during dotfiles installation otherwise run `sudo unminimize` manually
# https://wiki.ubuntu.com/Minimal
unminimize: false
prompt:
  zsh:
    repo: nojhan/liquidprompt
    branch: stable
    dest: "~/.liquidprompt"
  bash:
    repo: nojhan/liquidprompt
    branch: stable
    dest: "~/.liquidprompt"
packages:
  # use apt for packages that don't get updated as frequently
  apt: ["git-extras", "ripgrep", "shellcheck", "vim"]
  github:
    - bin: gh
      repo: cli/cli
      arch: linux_amd64
    - repo: sharkdp/bat # the one in apt is old
      arch: amd64
    - repo: sharkdp/fd
      arch: amd64
    - repo: dandavison/delta
      arch: amd64
    - repo: peltoche/lsd
      arch: amd64
    - repo: ajeetdsouza/zoxide
      arch: amd64
